### ISSUE TITLE
Bump version on npm

### ISSUE THREAD

**Issue by kbiedrzycki** [jesusoterogomez/react-notify-toast#11]
Can you bump version of library available on npm? You've merged my PR some time ago, but I cannot access those changes without bumping version on npm. Thanks @jesusoterogomez!

**Comment by kbiedrzycki** [comment]
I've opened PR for that #12

**Comment by jesusoterogomez** [comment]
I'm sorry, I will have to re-bump the version, it seems that I have already pushed 0.1.1 some time ago, and I didn't include the version change in a commit. 

You'll find your changes in `0.1.2`, I am going to commit a Travis CI build script to have the npm releases in sync on each tagged release.
