### ISSUE TITLE
Styling

### ISSUE THREAD

**Issue by gridworkz** [jesusoterogomez/react-notify-toast#18]
Hi:

How do you style the component?

Cheers,
Dave (Newbie)

**Comment by donsalari** [comment]
Currently you cannot.

**Comment by jesusoterogomez** [comment]
@gridworkz #20 will be merged soon and will allow you make some basic styling (i.e. background and text color). I will close this issue once it's released.

Thanks for your contribution @donsalari.

**Comment by gridworkz** [comment]
Thanks so much!

**Comment by jesusoterogomez** [comment]
Closed by #20
