### ISSUE TITLE
Inserting links using react-router Link in toast content

### ISSUE THREAD

**Issue by bnlambert** [jesusoterogomez/react-notify-toast#19]
Hi, I am actually enjoying react-notify-toast, great job. 
In my react project, there are moments that the network temporarily fails but loads on refresh. I want to insert a link in my notification that will permit end users to click on it to refresh the page in case of any network error.
I have tried but all the content has been escape. Any ideas? Thanks

**Comment by jesusoterogomez** [comment]
Hi, thank you for your feedback.

Right now the component is accepting the content (prop `text`) as a `string`. But I believe this content should not get escaped because of this.

I will modify the component to also accept other types of content. (I am working on a rewrite that will make this cleaner, anyways).

For the time being. I just tried this approach, and it renders fine as a link, of course, with the warnings in the console due to not matching the input type.

```js
notify.show(<Link to="/login">This is just a test</Link>, 5000);
```

**Comment by jesusoterogomez** [comment]
Oh, I just realized the react router Link will not work in this way...
You will get this message.

```Uncaught Error: <Link>s rendered outside of a router context cannot navigate.``` Which makes sense.

Though you may be able to use an easy workaround, by generating your href link from React Router.
(The API might differ based on your `react-router` version).

```js
// Get router from context.
let {router} = this.context;

// Generate an href url to your desired route.
let link = router.createHref({
     name: 'home',
     params: {foo: 'bar'}
});

// Use the generated link in an <a> tag.
notify.show(<a href={link}>This is just a test</a>, 5000);
```

Another option is to add a `<span>` or an `<a>` tag to the content of the tooltip that includes an `onClick` handler that performs the redirection for you, via your preferred method. (window.location / router.push / router.transitionTo, etc... )

**Comment by bnlambert** [comment]
I started working on another version of your work. Just got busy. I have modified the propTypes of 'text' to `text: PropTypes.oneOfType([
	        PropTypes.string,
			PropTypes.element,
	    ]),`

I simply need to test it. But you can move ahead. Please let me know what it gives.
Courage.
