### ISSUE TITLE
Support for Multiline?

### ISSUE THREAD

**Issue by araneta** [jesusoterogomez/react-notify-toast#26]
I tried to show a notification notify.show(errors.join('<br />'),'error'); but it show weird notification. is this module support multiline <br /> ?

**Comment by jesusoterogomez** [comment]
I have to test if `<br/>` is compatible with this module. But my initial thought is that it's not. There was a PR created for supporting multiline text (at least 2 lines of it). but it wasn't merged due to the approach taken, since it was going to affect the single line text rendering.

**Comment by araneta** [comment]
so what is the solutions for this? thanks

**Comment by stephenfeather** [comment]
The css hack works as long as I don't have 3 lines of text.  If we stretch into 3 lines, then when the toast clears, it leaves about half a line exposed.  May explain part of the question I had in #44
