### ISSUE TITLE
Create New Release

### ISSUE THREAD

**Issue by alsiola** [jesusoterogomez/react-notify-toast#27]
Many thanks for incorporating the notification feature #22 into master (and for fixing the linting errors 👍 )

Could you publish a new release to NPM from current version of master?

Unrelated note: Do you think there it would be worthwhile to create a demo page showing the appearance of notifications?  I know when I was looking for a notification library this would have been helpful to me.  If so then I am happy to put together a demo page.

Many thanks,
Alex

**Comment by jesusoterogomez** [comment]
Thanks for reminding me that I hadn't bumped the version. I have made a PR which will make the release via Travis.

As for the unrelated note. on the branch `dev-channel` I had been working on an examples page. But I just realized, for the sake of simplicity. I will include a couple of GIFs on the `README` which will basically achieve the same goal.

**Comment by jesusoterogomez** [comment]
(It seems that the Travis script is not releasing automatically to npm, I will make sure it does or release it manually)

**Comment by jesusoterogomez** [comment]
All good and ready to go, `0.1.5` is live
