### ISSUE TITLE
Setting Container style

### ISSUE THREAD

**Issue by gnanaprakash** [jesusoterogomez/react-notify-toast#30]
Can you provide the support to set style for container? since I need to set z-index attribute of the container to much higher value that the default of 999

**Comment by jesusoterogomez** [comment]
Hello. I will try to make this happen during the weekend. I think I'm going to release a major version that changes the API a bit but that will make it easier to include custom settings such as this one.

**Comment by gnanaprakash** [comment]
Thanks. Looking forward

**Comment by jesusoterogomez** [comment]
This is now possible as of `0.3.1`. Look at the README to find the instructions if you still need this :).
