### ISSUE TITLE
Not work with the `AppBar` componnet from Material-UI

### ISSUE THREAD

**Issue by MonFig** [jesusoterogomez/react-notify-toast#31]
When I use the `AppBar` component from Material-UI, I found the z-index(might be) of the toast is too small to display the notification. 

Maybe we can use some arguments to reset the stylesheet of the toast, to set its `margin-top` or `z-index`.

Hope you a good day.

**Comment by gnyani** [comment]
Even I am facing the same issue with `AppBar ` , Is there a way to set zDepth to `notify.show()` method?

**Comment by jesusoterogomez** [comment]
There is partial support for this in the new release (`0.3.0`).

You can override some default values. This will be added to a documentation section.

You can do so by passing an options prop to the `<Notification>` component.

```js
<Notification options={{zIndex: 5000}} />
```
This options property can be used to override any value in `src/defaults.js`. Keep in mind that it can only override topmost values, and not nested values. (i.e. not a deep merge, but a shallow assign).

**Comment by jesusoterogomez** [comment]
I say "partial support" because there's still no way to override the margins and other styling for example. But I made code changes to allow for this to be implemented soon.

**Comment by gnyani** [comment]
@jesusoterogomez  thank you so much for getting this done quickly.

**Comment by MonFig** [comment]
@gnyani You're so lucky, while I've waited for a long time 😂

**Comment by jesusoterogomez** [comment]
I'm really sorry for the delay, guys. Time is relative 😆
