### ISSUE TITLE
Accessing PropTypes via the main React package is deprecated

### ISSUE THREAD

**Issue by sethreidnz** [jesusoterogomez/react-notify-toast#32]
With the latest version of React this gives the error "Accessing PropTypes via the main React package is deprecated". We must now use 'prop-types' package.

I am going to create a pull-request for this but thought I'd raise an issue first to see if any objects. Will be a two lines in two files.

**Comment by sethreidnz** [comment]
#33

**Comment by sethreidnz** [comment]
Any thoughts on merge?

**Comment by jesusoterogomez** [comment]
Closed by #33
