### ISSUE TITLE
set z-index dynamically 

### ISSUE THREAD

**Issue by soumen55** [jesusoterogomez/react-notify-toast#36]
How I can set z-index dynamically ?

**Comment by jesusoterogomez** [comment]
This is supported from `0.3.0` by overriding the default values. This will be added to a documentation section.

You can do so by passing an options prop to the `<Notification>` component.

```js
<Notification options={{zIndex: 5000}} />
```
This options property can be used to override any value in `src/defaults.js`. Keep in mind that it can only override topmost values, and not nested values. (i.e. not a deep merge, but a shallow assign).
