### ISSUE TITLE
Error: Cannot find module 'p-map'

### ISSUE THREAD

**Issue by bryanleejh** [jesusoterogomez/react-notify-toast#37]
Getting this error when I'm trying to use the react-notify-toast module. Not sure what's going on.

**Comment by jesusoterogomez** [comment]
Hello @bryanleejh . I wasn't able to find `p-map` as a dependency (or subdependency) anywhere in this module. So I can't help much with figuring out why you're getting this error.

Can you try this in your console, in your project's directory?
`npm ls | grep p-map`. Do you get any results?

**Comment by bryanleejh** [comment]
Hmm will try it out! Thanks! @jesusoterogomez I ended up just rendering a component to display errors instead cause I was trying to meet a deadline. Appreciate your help though!
