### ISSUE TITLE
Maintain changelog

### ISSUE THREAD

**Issue by stjepan** [jesusoterogomez/react-notify-toast#38]
Hi,

The current version seems to be 0.3.0 but there is no information about what happened between 0.2.0 and that one. The same goes on for couple versions behind.

The lack of information makes it hard to decide if I could or should update. Of course I want to always be on the latest version, but I also want to know of any breaking changes that might occur, even if you follow semantic versioning (according to the change log file).

Could you please update the information and also not forget about that in the future? :)

/S.

**Comment by jesusoterogomez** [comment]
Hello @stjepan . You're very right, and I honestly have been very sloppy while updating the Changelog when I have updated this package the last couple of times.

The next time I do an update I will keep this in mind and I will back-fill the missing data soon and reply in this thread when I do so :).

**Comment by jesusoterogomez** [comment]
I have added information for previous versions. I also noticed that Travis was not pushing my tags as intended, so figuring everything was trickier than expected (And I might have missed a couple of minor details, but the important stuff is in there now).

Thank you for the recommendation.

I feel kind of ashamed considering that I'm usually strict about these things 😆

**Comment by stjepan** [comment]
👍🏻
