### ISSUE TITLE
Target container is not a DOM element.

### ISSUE THREAD

**Issue by Benjamin-Daniel** [jesusoterogomez/react-notify-toast#47]
invariant.js:42 Uncaught Error: unmountComponentAtNode(...): Target container is not a DOM element.
    at invariant (invariant.js:42)
    at Object.unmountComponentAtNode (ReactMount.js:438)
    at hide (notify.js:37)
    at notify.js:68

**Comment by debugpoint136** [comment]
Same issue here. @Benjamin-Daniel Can you explain how you resolved this please?

**Comment by Benjamin-Daniel** [comment]
I can't remember
