### ISSUE TITLE
Error on getElementById

### ISSUE THREAD

**Issue by ulisescarreonalvarez** [jesusoterogomez/react-notify-toast#57]
Hi everyone,

First of all greate component i really like it, i'm working on a webapp actually my code looks like this:

```
import React, { Component } from 'react';
import PropTypes from 'prop-types';
import Backend from '../Layouts/Backend';
import { InfoboxProject } from '../UI/Infobox';
import { connect } from 'react-redux';
import { actionCreators } from '../../actions';
import Loading from '../Helpers/Loading';
import Rodal from 'rodal';
import { withRouter } from 'react-router';
import { Button } from 'semantic-ui-react'
import Notifications, {notify} from 'react-notify-toast';

class Clients extends Component {
    constructor(props) {
        super(props);  
        this.state = { visible: false, item: null };          
    }
    
    componentWillMount(){
        const token = localStorage.getItem('token');
        if (typeof token == 'undefined' || token == null)
        {
            this.props.history.push('/login');
        }        
    }

    componentDidMount() {
         this.props.dispatch(actionCreators.fetchClients());
     }
     
    show(item) {
        this.setState({ visible: true, name: item });
    }

    hide() {
        this.setState({ visible: false });
    }

    componentWillReceiveProps(nextProps){
  if(typeof nextProps.clients != "undefined" && nextProps.clients != null && nextProps.clients.length != null && nextProps.clients.length > 0){}
            let myColor = { background: '#f44242', text: "#FFFFFF" };
            notify.show("No cuentas actualmente con clientes", "custom", 5000, myColor); 
        }

    }

    render() {
        let results = this.props.clients.map((client) => {
            return <ClientExtend key={client.debtorno} client={client} datClick={this.show.bind(this)}/>
        });

        return (
            
            this.props.isFetching ? <Backend><div className="content-inner"><Loading /></div></Backend> :
            <Backend>     
                <Rodal visible={this.state.visible} onClose={this.hide.bind(this)}>
                    <div>{this.state.nombre}</div>
                </Rodal>           
                <div className='main'>
		    	<Notifications />
    		</div>
                <div className="content-inner">
                    <div className="table-responsive">
                        <table>
                            <tbody>
                                {results}
                            </tbody>
                        </table>
                    </div>
                </div>
            </Backend>
        );
    }
}

Clients.propTypes = {
    dispatch: PropTypes.func,
    isFetching: PropTypes.bool.isRequired,
    clients: PropTypes.array.isRequired

};

Clients.contextTypes = {
    router: PropTypes.object.isRequired
};

export default connect((store) => {
  return {
        clients: store.clientState.data,
        pagination: store.clientState.pagination,
        isFetching: store.clientState.isFetching
  };
})(Clients)


class ClientExtend extends Component {

    constructor(props) {
        super(props); 
    }

    assignItemModal(item) {
        this.props.datClick(item);
    }

    render() {
        return (
            <tr>
                <td className="min-width">              

                    <div className="title-wrapper">
                        <div className="title">Name</div>
                        <div className="subtitle">{this.props.client.nombre} {this.props.client.nombre}</div>
                    </div>
                </td>
                <td>
                    <div className="key-value">
                        <span>Email</span>
                        <strong>{this.props.client.email}</strong>
                    </div>
                </td>
                <td>
                    <div className="key-value">
                        <span>Phone</span>
                        <strong>{this.props.client.razon_social}</strong>
                    </div>
                </td>
                <td className="actions min-width">
                    <div className="button-group">
                        <Button color="black" onClick={this.assignItemModal.bind(this, this.props.client.nombre)}>Edit</Button>
                        <Button color="red" onClick={this.assignItemModal.bind(this, this.props.client.nombre)}>Delete</Button>
                    </div>
                </td>
            </tr>
        );
    }
}
```

When my prop "clients" is empty i wanna show a toast but i'm having this error:

```
TypeError: document.getElementById(...) is null
show
node_modules/react-notify-toast/bin/notify.js:55

  52 |  * }
  53 |  */
  54 | function show(text, type, timeout, color) {
> 55 |     if (!document.getElementById(_defaults.defaults.wrapperId).hasChildNodes()) {
  56 |         // Use default timeout if not set.
  57 |         var renderTimeout = timeout || _defaults.defaults.timeout;
  58 | 

componentWillReceiveProps
src/components/Pages/Clients.js:43

  40 |     console.log(nextProps.clients.lenght);
  41 |     if(typeof nextProps.clients.lenght ==='undefined'){
  42 |         let myColor = { background: '#f44242', text: "#FFFFFF" };
> 43 |         notify.show("No cuentas actualmente con clientes", "custom", 5000, myColor); 
  44 |     }
  45 | 
  46 | }

fetchClients/</<
src/actions/clients.js:25

  22 |           dataFetched: true
  23 |       });
  24 | }else{
> 25 |   dispatch({
  26 |       type: types.FETCHING_CLIENTS_FAILURE,
  27 |       isFetching: false,
  28 |       error: true,
```
What am i missing? 

Regards

**Comment by jesusoterogomez** [comment]
Hola Ulises! gracias por los buenos comentarios. Voy a responder el mensaje en inglés porque es posible que pueda ayudar a alguien mas con el mismo problema.

I haven't fully reversed-engineered your example, but a likely scenario, is that `<Notifications/>` is being unmounted when `clients` is undefined. However, the code doesn't seem to have this issue.

The issue that I see, is that on `src/components/Pages/Clients.js:41`. I see `nextProps.clients.lenght` instead of `nextPros.clients.length` (*lenght  > length* is misspelled).

I don't know if length is expected to be a custom property of your object. but if the data type of this property is an array, then you should check it with `nextProps.clients.length === 0` or `typeof nextProps.clients === "undefined"` if you are expecting it to be undefined at some point. (Which shouldn't happen given your PropTypes definition)

**Comment by jesusoterogomez** [comment]
Actually, it might be because of the first issue I described. Make sure `<Notifications/>` is always mounted and not put inside any conditional code.

**Comment by ulisescarreonalvarez** [comment]
Hi Jesus, i fix my mistake of the "length", but the same error.

```
  componentWillReceiveProps(nextProps){
        if(typeof nextProps.clients.length ==='undefined' || nextProps.clients.length === 0 ){
            let myColor = { background: '#f44242', text: "#FFFFFF" };
            notify.show("No cuentas actualmente con clientes", "custom", 5000, myColor); 
        }
    }
```
I'm tryng to locate on the correct way the component but still shows  the error:

![captura de pantalla 2018-05-28 a la s 10 07 33](https://user-images.githubusercontent.com/25987364/40620588-fa57198a-625e-11e8-88fe-9c2f4cb5ce28.png)

**Comment by jesusoterogomez** [comment]
Can you try to check with the react tools if <Notification/> is rendered with the state?  I believe this component may be getting unmounted

**Comment by jesusoterogomez** [comment]
Can you try making an extra div in your render function and moving the Notification component one level outside your `isFetching` logic?  In

**Comment by ulisescarreonalvarez** [comment]
Hi, i tried what you say, if if put my component on the top will work, but why not in a lower level?:

![captura de pantalla 2018-05-28 a la s 10 18 36](https://user-images.githubusercontent.com/25987364/40620995-9ede1d2c-6260-11e8-9e36-2b47d0df0532.png)
![captura de pantalla 2018-05-28 a la s 10 18 30](https://user-images.githubusercontent.com/25987364/40620996-9ef5fabe-6260-11e8-93ec-c9b1a53f8b99.png)

**Comment by jesusoterogomez** [comment]
How about this?

```
render() {
    let results = this.props.clients.map((client) => {
        return <ClientExtend key={client.debtorno} client={client} datClick={this.show.bind(this)}/>
    });

    return (
        <Backend>
            <Notifications />
            {this.props.isFetching ?
                <div className="content-inner"><Loading /></div>
                :
                <div>
                    <Rodal visible={this.state.visible} onClose={this.hide.bind(this)}>
                        <div>{this.state.nombre}</div>
                    </Rodal>     
                    <div className="content-inner">
                        <div className="table-responsive">
                            <table>
                                <tbody>
                                    {results}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            }
        </Backend>
    );
}
```

I made a small refactoring, by only rendering the different states inside the isFetching conditional. I moved `Backend` to the outer level of the JSX markup to avoid duplicating that component. It should behave in the same way as your app should.

**Comment by ulisescarreonalvarez** [comment]
It's works now but, i have a new issue when i change my Backend Component :/
When is fetching its shows tow backends:

<img width="924" alt="captura de pantalla 2018-05-28 a la s 17 05 41" src="https://user-images.githubusercontent.com/25987364/40630619-a5e91afc-6299-11e8-97dc-5d28b45675db.png">

And when it finish:

![captura de pantalla 2018-05-28 a la s 17 05 52](https://user-images.githubusercontent.com/25987364/40630629-b04c8d3a-6299-11e8-9e2b-b5262103a1cd.png)

Maybe move the backend make it work but the Component appers for seconds .

Any advice? :/

**Comment by jesusoterogomez** [comment]
I may have broken something with my refactor. But I can't see anything obviously wrong in the code. Try commenting out the Notification and tell me if it's still happening. 

If it still happens, maybe it could be something else in your codebase. Maybe `Loading` also contains a Backend component?

I also think you misunderstood a bit the implementation in the README. If you put `Notification` in your entry point of the app. (Usually app.jsx/index.jsx) then you wouldn't have to worry about this issue, and it would allow you to use notify anywhere else in your application.

**Comment by jesusoterogomez** [comment]
Okay. I see the problem. 

In this line 

`{this.props.isFetching ? <Backend><div className="content-inner"><Loading /></div></Backend> : ...`

You are using Backend again.

You can copy and paste the full render function from my previous comment. 

Short explanation. You have a Backend component that contains all the rest of the code as a "child". You shouldn't add Backend as a child again.

If you look closely, I removed it in my example.

In Spanish: la idea es que uses la función `render` de mi ejemplo completa. No fue solo una correción de una línea. Copia y reemplaza la función entera y debería funcionar a la perfección.

**Comment by ulisescarreonalvarez** [comment]
Damn, you are right i forget about that Backend on the fetching, that solves the problem!
Thank you!

**Comment by jesusoterogomez** [comment]
No problem! I will close the issue. Good luck on your project
