### ISSUE TITLE
Uncaught TypeError: Cannot read property 'hasChildNodes' of null

### ISSUE THREAD

**Issue by Danny-G-Smith** [jesusoterogomez/react-notify-toast#62]
This may be operator error, I am trying to figure out how to use it and am new to react.  I created a new install with npx create-react-app notifications, and added react-notify-toast via, npm install react-notify-toast --save.  This is the contents of App.js:

![image 2018-09-22 at 12 50 26 pm](https://user-images.githubusercontent.com/33608173/45920157-1dc21380-be66-11e8-9770-9268982938d6.png)

**Comment by ARKKYN** [comment]
please try to move notification component to higher dom position as possible @Danny-G-Smith  I had same kid of issue it fixed it

**Comment by jesusoterogomez** [comment]
Thanks @ARKKYN.
@Danny-G-Smith this actually happens because the `note()` function is attempting to show the notification on an element that hasn't been rendered previously. 

Since the application only needs the `<Notifications/>` element once, I recommend that you add it under the `"div.App"`.

If you need any extra help, just let me know.

**Comment by jesusoterogomez** [comment]
I'm closing this issue since it was an issue in the implementation of the feature instead of the library itself. If anyone stumbles across this again, just let me know :)

**Comment by nmihaica** [comment]
While using Gatsby, it worked in development, but not in production.
 ```
Uncaught (in promise) TypeError: Cannot read property 'hasChildNodes' of null
    at Object.s [as show] (notify.js:55)
```
EDIT:

Top level.
```
import React from 'react'
import Notifications from 'react-notify-toast';

export const wrapRootElement = ({ element }) => {
  return (
    <div className="wrap-root">
      <Notifications options={{zIndex: 200, top: '24px'}} />
      {element}
    </div>
  )
}
```

**Comment by ARKKYN** [comment]
@nmihaica  try to wrap it without wrap-root . instead replace that div with <> </> or <React.Fragment></React.Fragment>

**Comment by nmihaica** [comment]
Solved.

Silly mistake. Forgot to copy also to `gatsby-ssr` that's why it worked in `development` but not in `production`. Not needed to wrap it inside fragment. Thanks anyway.
