### ISSUE TITLE
Get rid of deprecated `componentWillMount` to stop React warnings

### ISSUE THREAD

**Issue by today-** [jesusoterogomez/react-notify-toast#68]
`componentWillMount` is marked as deprecated in React (since 16.3) and will be removed in next major version https://medium.com/@baphemot/whats-new-in-react-16-3-d2c9b7b6193b

So it's necessary to replace it in Container component:
https://github.com/jesusoterogomez/react-notify-toast/blob/master/src/components/Container.js#L15

**Comment by jesusoterogomez** [comment]
Closed by #69

**Comment by jesusoterogomez** [comment]
Available in https://github.com/jesusoterogomez/react-notify-toast/releases/tag/0.5.1
